#include<stdio.h>
int main()
{
	int p,q,i,j,a[100001],b[100001],k,c[100001],r,test,t,temp;
	long long int sum,count1[100001],count2[100001];
	scanf("%d",&test);
	for(t=0;t<test;t++)
	{
		for(i=0;i<=100001;i++)
			count1[i]=0;
		for(i=0;i<=100001;i++)
			count2[i]=0;
		sum=0;
		scanf("%d",&p);
		for(i=0;i<p;i++)
			scanf("%d",&a[i]);
		scanf("%d",&q);
		for(i=0;i<q;i++)
			scanf("%d",&b[i]);
		scanf("%d",&r);
		for(i=0;i<r;i++)
			scanf("%d",&c[i]);
		i=0;j=0;
		while((i<q)&&(j<p))
		{
			if((b[i]<a[j])||(i<j))
			{
				count1[i]=j;
				i++;
			}
			else
				j++;
		}
		if(j==p){
			for(k=i;k<q;k++)
			{
				count1[k]=p;
			}
		}
		i=j=0;
		while((i<r)&&(j<q))
		{
			if((c[i]<b[j])||(i<j))
			{
				count2[i]=j;
				i++;
			}
			else
				j++;
		}
		if(j==q)
		{
			for(k=i;k<r;k++)
			{
				count2[k]=q;
			}
		}
		for(i=1;i<q;i++)
			count1[i]=count1[i-1]+count1[i];
		for(j=0;j<r;j++)
			sum+=count1[count2[j]-1];
		printf("%Ld\n",sum);
	}
	return 0;
}
